/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestErrorRouteImport } from './routes/test-error'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeviceIndexRouteImport } from './routes/device/index'
import { Route as PublicProjectProjectIdRouteImport } from './routes/public-project.$projectId'
import { Route as DeviceApproveRouteImport } from './routes/device/approve'
import { Route as AuthVerifyOtpRouteImport } from './routes/auth/verify-otp'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthCheckEmailRouteImport } from './routes/auth/check-email'
import { Route as LayoutAuthenticatedRouteImport } from './routes/_layout/_authenticated'
import { Route as InvitationAcceptInviteIdRouteImport } from './routes/invitation/accept.$inviteId'
import { Route as LayoutAuthenticatedProfileSetupRouteImport } from './routes/_layout/_authenticated/profile-setup'
import { Route as LayoutAuthenticatedOnboardingRouteImport } from './routes/_layout/_authenticated/onboarding'
import { Route as LayoutAuthenticatedInvitationsRouteImport } from './routes/_layout/_authenticated/invitations'
import { Route as LayoutAuthenticatedDashboardRouteImport } from './routes/_layout/_authenticated/dashboard'
import { Route as LayoutAuthenticatedDashboardIndexRouteImport } from './routes/_layout/_authenticated/dashboard/index'
import { Route as LayoutAuthenticatedDashboardSettingsRouteImport } from './routes/_layout/_authenticated/dashboard/settings'
import { Route as LayoutAuthenticatedDashboardInvitationsRouteImport } from './routes/_layout/_authenticated/dashboard/invitations'
import { Route as LayoutAuthenticatedDashboardWorkspaceCreateRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/create'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId'
import { Route as LayoutAuthenticatedDashboardSettingsWorkspaceRouteImport } from './routes/_layout/_authenticated/dashboard/settings/workspace'
import { Route as LayoutAuthenticatedDashboardSettingsProjectsRouteImport } from './routes/_layout/_authenticated/dashboard/settings/projects'
import { Route as LayoutAuthenticatedDashboardSettingsAccountRouteImport } from './routes/_layout/_authenticated/dashboard/settings/account'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/index'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/search'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdOverviewRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/overview'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMyTasksRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/my-tasks'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/members'
import { Route as LayoutAuthenticatedDashboardSettingsWorkspaceRolesRouteImport } from './routes/_layout/_authenticated/dashboard/settings/workspace/roles'
import { Route as LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRouteImport } from './routes/_layout/_authenticated/dashboard/settings/workspace/general'
import { Route as LayoutAuthenticatedDashboardSettingsAccountSecurityRouteImport } from './routes/_layout/_authenticated/dashboard/settings/account/security'
import { Route as LayoutAuthenticatedDashboardSettingsAccountPreferencesRouteImport } from './routes/_layout/_authenticated/dashboard/settings/account/preferences'
import { Route as LayoutAuthenticatedDashboardSettingsAccountNotificationsRouteImport } from './routes/_layout/_authenticated/dashboard/settings/account/notifications'
import { Route as LayoutAuthenticatedDashboardSettingsAccountInformationRouteImport } from './routes/_layout/_authenticated/dashboard/settings/account/information'
import { Route as LayoutAuthenticatedDashboardSettingsAccountDeveloperRouteImport } from './routes/_layout/_authenticated/dashboard/settings/account/developer'
import { Route as LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRouteImport } from './routes/_layout/_authenticated/dashboard/settings/projects/$projectId/workflow'
import { Route as LayoutAuthenticatedDashboardSettingsProjectsProjectIdVisibilityRouteImport } from './routes/_layout/_authenticated/dashboard/settings/projects/$projectId/visibility'
import { Route as LayoutAuthenticatedDashboardSettingsProjectsProjectIdRolesRouteImport } from './routes/_layout/_authenticated/dashboard/settings/projects/$projectId/roles'
import { Route as LayoutAuthenticatedDashboardSettingsProjectsProjectIdMembersRouteImport } from './routes/_layout/_authenticated/dashboard/settings/projects/$projectId/members'
import { Route as LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRouteImport } from './routes/_layout/_authenticated/dashboard/settings/projects/$projectId/integrations'
import { Route as LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRouteImport } from './routes/_layout/_authenticated/dashboard/settings/projects/$projectId/general'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdIndexRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/index'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdSprintsRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/sprints'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdGanttRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/gantt'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdDocumentsRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/documents'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBoardRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/board'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/backlog'
import { Route as LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRouteImport } from './routes/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId_'

const TestErrorRoute = TestErrorRouteImport.update({
  id: '/test-error',
  path: '/test-error',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceIndexRoute = DeviceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeviceRoute,
} as any)
const PublicProjectProjectIdRoute = PublicProjectProjectIdRouteImport.update({
  id: '/public-project/$projectId',
  path: '/public-project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceApproveRoute = DeviceApproveRouteImport.update({
  id: '/approve',
  path: '/approve',
  getParentRoute: () => DeviceRoute,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCheckEmailRoute = AuthCheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => AuthRoute,
} as any)
const LayoutAuthenticatedRoute = LayoutAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => LayoutRoute,
} as any)
const InvitationAcceptInviteIdRoute =
  InvitationAcceptInviteIdRouteImport.update({
    id: '/invitation/accept/$inviteId',
    path: '/invitation/accept/$inviteId',
    getParentRoute: () => rootRouteImport,
  } as any)
const LayoutAuthenticatedProfileSetupRoute =
  LayoutAuthenticatedProfileSetupRouteImport.update({
    id: '/profile-setup',
    path: '/profile-setup',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedOnboardingRoute =
  LayoutAuthenticatedOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedInvitationsRoute =
  LayoutAuthenticatedInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedDashboardRoute =
  LayoutAuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedDashboardIndexRoute =
  LayoutAuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsRoute =
  LayoutAuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardInvitationsRoute =
  LayoutAuthenticatedDashboardInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardWorkspaceCreateRoute =
  LayoutAuthenticatedDashboardWorkspaceCreateRouteImport.update({
    id: '/workspace/create',
    path: '/workspace/create',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteImport.update({
    id: '/workspace/$workspaceId',
    path: '/workspace/$workspaceId',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsWorkspaceRoute =
  LayoutAuthenticatedDashboardSettingsWorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsProjectsRoute =
  LayoutAuthenticatedDashboardSettingsProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAccountRoute =
  LayoutAuthenticatedDashboardSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsRoute,
  } as any)
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
  } as any)
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
  } as any)
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdOverviewRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
  } as any)
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMyTasksRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMyTasksRouteImport.update({
    id: '/my-tasks',
    path: '/my-tasks',
    getParentRoute: () => LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
  } as any)
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsWorkspaceRolesRoute =
  LayoutAuthenticatedDashboardSettingsWorkspaceRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsWorkspaceRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRoute =
  LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsWorkspaceRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAccountSecurityRoute =
  LayoutAuthenticatedDashboardSettingsAccountSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsAccountRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute =
  LayoutAuthenticatedDashboardSettingsAccountPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsAccountRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute =
  LayoutAuthenticatedDashboardSettingsAccountNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsAccountRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAccountInformationRoute =
  LayoutAuthenticatedDashboardSettingsAccountInformationRouteImport.update({
    id: '/information',
    path: '/information',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsAccountRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute =
  LayoutAuthenticatedDashboardSettingsAccountDeveloperRouteImport.update({
    id: '/developer',
    path: '/developer',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsAccountRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRoute =
  LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRouteImport.update(
    {
      id: '/$projectId/workflow',
      path: '/$projectId/workflow',
      getParentRoute: () => LayoutAuthenticatedDashboardSettingsProjectsRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardSettingsProjectsProjectIdVisibilityRoute =
  LayoutAuthenticatedDashboardSettingsProjectsProjectIdVisibilityRouteImport.update(
    {
      id: '/$projectId/visibility',
      path: '/$projectId/visibility',
      getParentRoute: () => LayoutAuthenticatedDashboardSettingsProjectsRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardSettingsProjectsProjectIdRolesRoute =
  LayoutAuthenticatedDashboardSettingsProjectsProjectIdRolesRouteImport.update({
    id: '/$projectId/roles',
    path: '/$projectId/roles',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsProjectsRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsProjectsProjectIdMembersRoute =
  LayoutAuthenticatedDashboardSettingsProjectsProjectIdMembersRouteImport.update(
    {
      id: '/$projectId/members',
      path: '/$projectId/members',
      getParentRoute: () => LayoutAuthenticatedDashboardSettingsProjectsRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRoute =
  LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRouteImport.update(
    {
      id: '/$projectId/integrations',
      path: '/$projectId/integrations',
      getParentRoute: () => LayoutAuthenticatedDashboardSettingsProjectsRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRoute =
  LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRouteImport.update(
    {
      id: '/$projectId/general',
      path: '/$projectId/general',
      getParentRoute: () => LayoutAuthenticatedDashboardSettingsProjectsRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdIndexRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdIndexRouteImport.update(
    {
      id: '/project/$projectId/',
      path: '/project/$projectId/',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdSprintsRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdSprintsRouteImport.update(
    {
      id: '/project/$projectId/sprints',
      path: '/project/$projectId/sprints',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdGanttRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdGanttRouteImport.update(
    {
      id: '/project/$projectId/gantt',
      path: '/project/$projectId/gantt',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdDocumentsRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdDocumentsRouteImport.update(
    {
      id: '/project/$projectId/documents',
      path: '/project/$projectId/documents',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBoardRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBoardRouteImport.update(
    {
      id: '/project/$projectId/board',
      path: '/project/$projectId/board',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRouteImport.update(
    {
      id: '/project/$projectId/backlog',
      path: '/project/$projectId/backlog',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRoute =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRouteImport.update(
    {
      id: '/project/$projectId/task/$taskId_',
      path: '/project/$projectId/task/$taskId',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/device': typeof DeviceRouteWithChildren
  '/test-error': typeof TestErrorRoute
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/device/approve': typeof DeviceApproveRoute
  '/public-project/$projectId': typeof PublicProjectProjectIdRoute
  '/device/': typeof DeviceIndexRoute
  '/dashboard': typeof LayoutAuthenticatedDashboardRouteWithChildren
  '/invitations': typeof LayoutAuthenticatedInvitationsRoute
  '/onboarding': typeof LayoutAuthenticatedOnboardingRoute
  '/profile-setup': typeof LayoutAuthenticatedProfileSetupRoute
  '/invitation/accept/$inviteId': typeof InvitationAcceptInviteIdRoute
  '/dashboard/invitations': typeof LayoutAuthenticatedDashboardInvitationsRoute
  '/dashboard/settings': typeof LayoutAuthenticatedDashboardSettingsRouteWithChildren
  '/dashboard/': typeof LayoutAuthenticatedDashboardIndexRoute
  '/dashboard/settings/account': typeof LayoutAuthenticatedDashboardSettingsAccountRouteWithChildren
  '/dashboard/settings/projects': typeof LayoutAuthenticatedDashboardSettingsProjectsRouteWithChildren
  '/dashboard/settings/workspace': typeof LayoutAuthenticatedDashboardSettingsWorkspaceRouteWithChildren
  '/dashboard/workspace/$workspaceId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteWithChildren
  '/dashboard/workspace/create': typeof LayoutAuthenticatedDashboardWorkspaceCreateRoute
  '/dashboard/settings/account/developer': typeof LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute
  '/dashboard/settings/account/information': typeof LayoutAuthenticatedDashboardSettingsAccountInformationRoute
  '/dashboard/settings/account/notifications': typeof LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute
  '/dashboard/settings/account/preferences': typeof LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute
  '/dashboard/settings/account/security': typeof LayoutAuthenticatedDashboardSettingsAccountSecurityRoute
  '/dashboard/settings/workspace/general': typeof LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRoute
  '/dashboard/settings/workspace/roles': typeof LayoutAuthenticatedDashboardSettingsWorkspaceRolesRoute
  '/dashboard/workspace/$workspaceId/members': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute
  '/dashboard/workspace/$workspaceId/my-tasks': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMyTasksRoute
  '/dashboard/workspace/$workspaceId/overview': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdOverviewRoute
  '/dashboard/workspace/$workspaceId/search': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute
  '/dashboard/workspace/$workspaceId/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute
  '/dashboard/settings/projects/$projectId/general': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRoute
  '/dashboard/settings/projects/$projectId/integrations': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRoute
  '/dashboard/settings/projects/$projectId/members': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdMembersRoute
  '/dashboard/settings/projects/$projectId/roles': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdRolesRoute
  '/dashboard/settings/projects/$projectId/visibility': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdVisibilityRoute
  '/dashboard/settings/projects/$projectId/workflow': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/backlog': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/board': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBoardRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/documents': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdDocumentsRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/gantt': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdGanttRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/sprints': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdSprintsRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdIndexRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/test-error': typeof TestErrorRoute
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/device/approve': typeof DeviceApproveRoute
  '/public-project/$projectId': typeof PublicProjectProjectIdRoute
  '/device': typeof DeviceIndexRoute
  '/invitations': typeof LayoutAuthenticatedInvitationsRoute
  '/onboarding': typeof LayoutAuthenticatedOnboardingRoute
  '/profile-setup': typeof LayoutAuthenticatedProfileSetupRoute
  '/invitation/accept/$inviteId': typeof InvitationAcceptInviteIdRoute
  '/dashboard/invitations': typeof LayoutAuthenticatedDashboardInvitationsRoute
  '/dashboard/settings': typeof LayoutAuthenticatedDashboardSettingsRouteWithChildren
  '/dashboard': typeof LayoutAuthenticatedDashboardIndexRoute
  '/dashboard/settings/account': typeof LayoutAuthenticatedDashboardSettingsAccountRouteWithChildren
  '/dashboard/settings/projects': typeof LayoutAuthenticatedDashboardSettingsProjectsRouteWithChildren
  '/dashboard/settings/workspace': typeof LayoutAuthenticatedDashboardSettingsWorkspaceRouteWithChildren
  '/dashboard/workspace/create': typeof LayoutAuthenticatedDashboardWorkspaceCreateRoute
  '/dashboard/settings/account/developer': typeof LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute
  '/dashboard/settings/account/information': typeof LayoutAuthenticatedDashboardSettingsAccountInformationRoute
  '/dashboard/settings/account/notifications': typeof LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute
  '/dashboard/settings/account/preferences': typeof LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute
  '/dashboard/settings/account/security': typeof LayoutAuthenticatedDashboardSettingsAccountSecurityRoute
  '/dashboard/settings/workspace/general': typeof LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRoute
  '/dashboard/settings/workspace/roles': typeof LayoutAuthenticatedDashboardSettingsWorkspaceRolesRoute
  '/dashboard/workspace/$workspaceId/members': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute
  '/dashboard/workspace/$workspaceId/my-tasks': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMyTasksRoute
  '/dashboard/workspace/$workspaceId/overview': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdOverviewRoute
  '/dashboard/workspace/$workspaceId/search': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute
  '/dashboard/workspace/$workspaceId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute
  '/dashboard/settings/projects/$projectId/general': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRoute
  '/dashboard/settings/projects/$projectId/integrations': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRoute
  '/dashboard/settings/projects/$projectId/members': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdMembersRoute
  '/dashboard/settings/projects/$projectId/roles': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdRolesRoute
  '/dashboard/settings/projects/$projectId/visibility': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdVisibilityRoute
  '/dashboard/settings/projects/$projectId/workflow': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/backlog': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/board': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBoardRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/documents': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdDocumentsRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/gantt': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdGanttRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/sprints': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdSprintsRoute
  '/dashboard/workspace/$workspaceId/project/$projectId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdIndexRoute
  '/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/device': typeof DeviceRouteWithChildren
  '/test-error': typeof TestErrorRoute
  '/_layout/_authenticated': typeof LayoutAuthenticatedRouteWithChildren
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/device/approve': typeof DeviceApproveRoute
  '/public-project/$projectId': typeof PublicProjectProjectIdRoute
  '/device/': typeof DeviceIndexRoute
  '/_layout/_authenticated/dashboard': typeof LayoutAuthenticatedDashboardRouteWithChildren
  '/_layout/_authenticated/invitations': typeof LayoutAuthenticatedInvitationsRoute
  '/_layout/_authenticated/onboarding': typeof LayoutAuthenticatedOnboardingRoute
  '/_layout/_authenticated/profile-setup': typeof LayoutAuthenticatedProfileSetupRoute
  '/invitation/accept/$inviteId': typeof InvitationAcceptInviteIdRoute
  '/_layout/_authenticated/dashboard/invitations': typeof LayoutAuthenticatedDashboardInvitationsRoute
  '/_layout/_authenticated/dashboard/settings': typeof LayoutAuthenticatedDashboardSettingsRouteWithChildren
  '/_layout/_authenticated/dashboard/': typeof LayoutAuthenticatedDashboardIndexRoute
  '/_layout/_authenticated/dashboard/settings/account': typeof LayoutAuthenticatedDashboardSettingsAccountRouteWithChildren
  '/_layout/_authenticated/dashboard/settings/projects': typeof LayoutAuthenticatedDashboardSettingsProjectsRouteWithChildren
  '/_layout/_authenticated/dashboard/settings/workspace': typeof LayoutAuthenticatedDashboardSettingsWorkspaceRouteWithChildren
  '/_layout/_authenticated/dashboard/workspace/$workspaceId': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteWithChildren
  '/_layout/_authenticated/dashboard/workspace/create': typeof LayoutAuthenticatedDashboardWorkspaceCreateRoute
  '/_layout/_authenticated/dashboard/settings/account/developer': typeof LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute
  '/_layout/_authenticated/dashboard/settings/account/information': typeof LayoutAuthenticatedDashboardSettingsAccountInformationRoute
  '/_layout/_authenticated/dashboard/settings/account/notifications': typeof LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute
  '/_layout/_authenticated/dashboard/settings/account/preferences': typeof LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute
  '/_layout/_authenticated/dashboard/settings/account/security': typeof LayoutAuthenticatedDashboardSettingsAccountSecurityRoute
  '/_layout/_authenticated/dashboard/settings/workspace/general': typeof LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRoute
  '/_layout/_authenticated/dashboard/settings/workspace/roles': typeof LayoutAuthenticatedDashboardSettingsWorkspaceRolesRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/members': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/my-tasks': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMyTasksRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/overview': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdOverviewRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/search': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute
  '/_layout/_authenticated/dashboard/settings/projects/$projectId/general': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRoute
  '/_layout/_authenticated/dashboard/settings/projects/$projectId/integrations': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRoute
  '/_layout/_authenticated/dashboard/settings/projects/$projectId/members': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdMembersRoute
  '/_layout/_authenticated/dashboard/settings/projects/$projectId/roles': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdRolesRoute
  '/_layout/_authenticated/dashboard/settings/projects/$projectId/visibility': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdVisibilityRoute
  '/_layout/_authenticated/dashboard/settings/projects/$projectId/workflow': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/backlog': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/board': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBoardRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/documents': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdDocumentsRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/gantt': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdGanttRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/sprints': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdSprintsRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdIndexRoute
  '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId_': typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/device'
    | '/test-error'
    | '/auth/check-email'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-otp'
    | '/device/approve'
    | '/public-project/$projectId'
    | '/device/'
    | '/dashboard'
    | '/invitations'
    | '/onboarding'
    | '/profile-setup'
    | '/invitation/accept/$inviteId'
    | '/dashboard/invitations'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/settings/account'
    | '/dashboard/settings/projects'
    | '/dashboard/settings/workspace'
    | '/dashboard/workspace/$workspaceId'
    | '/dashboard/workspace/create'
    | '/dashboard/settings/account/developer'
    | '/dashboard/settings/account/information'
    | '/dashboard/settings/account/notifications'
    | '/dashboard/settings/account/preferences'
    | '/dashboard/settings/account/security'
    | '/dashboard/settings/workspace/general'
    | '/dashboard/settings/workspace/roles'
    | '/dashboard/workspace/$workspaceId/members'
    | '/dashboard/workspace/$workspaceId/my-tasks'
    | '/dashboard/workspace/$workspaceId/overview'
    | '/dashboard/workspace/$workspaceId/search'
    | '/dashboard/workspace/$workspaceId/'
    | '/dashboard/settings/projects/$projectId/general'
    | '/dashboard/settings/projects/$projectId/integrations'
    | '/dashboard/settings/projects/$projectId/members'
    | '/dashboard/settings/projects/$projectId/roles'
    | '/dashboard/settings/projects/$projectId/visibility'
    | '/dashboard/settings/projects/$projectId/workflow'
    | '/dashboard/workspace/$workspaceId/project/$projectId/backlog'
    | '/dashboard/workspace/$workspaceId/project/$projectId/board'
    | '/dashboard/workspace/$workspaceId/project/$projectId/documents'
    | '/dashboard/workspace/$workspaceId/project/$projectId/gantt'
    | '/dashboard/workspace/$workspaceId/project/$projectId/sprints'
    | '/dashboard/workspace/$workspaceId/project/$projectId/'
    | '/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/test-error'
    | '/auth/check-email'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-otp'
    | '/device/approve'
    | '/public-project/$projectId'
    | '/device'
    | '/invitations'
    | '/onboarding'
    | '/profile-setup'
    | '/invitation/accept/$inviteId'
    | '/dashboard/invitations'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/settings/account'
    | '/dashboard/settings/projects'
    | '/dashboard/settings/workspace'
    | '/dashboard/workspace/create'
    | '/dashboard/settings/account/developer'
    | '/dashboard/settings/account/information'
    | '/dashboard/settings/account/notifications'
    | '/dashboard/settings/account/preferences'
    | '/dashboard/settings/account/security'
    | '/dashboard/settings/workspace/general'
    | '/dashboard/settings/workspace/roles'
    | '/dashboard/workspace/$workspaceId/members'
    | '/dashboard/workspace/$workspaceId/my-tasks'
    | '/dashboard/workspace/$workspaceId/overview'
    | '/dashboard/workspace/$workspaceId/search'
    | '/dashboard/workspace/$workspaceId'
    | '/dashboard/settings/projects/$projectId/general'
    | '/dashboard/settings/projects/$projectId/integrations'
    | '/dashboard/settings/projects/$projectId/members'
    | '/dashboard/settings/projects/$projectId/roles'
    | '/dashboard/settings/projects/$projectId/visibility'
    | '/dashboard/settings/projects/$projectId/workflow'
    | '/dashboard/workspace/$workspaceId/project/$projectId/backlog'
    | '/dashboard/workspace/$workspaceId/project/$projectId/board'
    | '/dashboard/workspace/$workspaceId/project/$projectId/documents'
    | '/dashboard/workspace/$workspaceId/project/$projectId/gantt'
    | '/dashboard/workspace/$workspaceId/project/$projectId/sprints'
    | '/dashboard/workspace/$workspaceId/project/$projectId'
    | '/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/auth'
    | '/device'
    | '/test-error'
    | '/_layout/_authenticated'
    | '/auth/check-email'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-otp'
    | '/device/approve'
    | '/public-project/$projectId'
    | '/device/'
    | '/_layout/_authenticated/dashboard'
    | '/_layout/_authenticated/invitations'
    | '/_layout/_authenticated/onboarding'
    | '/_layout/_authenticated/profile-setup'
    | '/invitation/accept/$inviteId'
    | '/_layout/_authenticated/dashboard/invitations'
    | '/_layout/_authenticated/dashboard/settings'
    | '/_layout/_authenticated/dashboard/'
    | '/_layout/_authenticated/dashboard/settings/account'
    | '/_layout/_authenticated/dashboard/settings/projects'
    | '/_layout/_authenticated/dashboard/settings/workspace'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId'
    | '/_layout/_authenticated/dashboard/workspace/create'
    | '/_layout/_authenticated/dashboard/settings/account/developer'
    | '/_layout/_authenticated/dashboard/settings/account/information'
    | '/_layout/_authenticated/dashboard/settings/account/notifications'
    | '/_layout/_authenticated/dashboard/settings/account/preferences'
    | '/_layout/_authenticated/dashboard/settings/account/security'
    | '/_layout/_authenticated/dashboard/settings/workspace/general'
    | '/_layout/_authenticated/dashboard/settings/workspace/roles'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/members'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/my-tasks'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/overview'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/search'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/'
    | '/_layout/_authenticated/dashboard/settings/projects/$projectId/general'
    | '/_layout/_authenticated/dashboard/settings/projects/$projectId/integrations'
    | '/_layout/_authenticated/dashboard/settings/projects/$projectId/members'
    | '/_layout/_authenticated/dashboard/settings/projects/$projectId/roles'
    | '/_layout/_authenticated/dashboard/settings/projects/$projectId/visibility'
    | '/_layout/_authenticated/dashboard/settings/projects/$projectId/workflow'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/backlog'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/board'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/documents'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/gantt'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/sprints'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/'
    | '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId_'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DeviceRoute: typeof DeviceRouteWithChildren
  TestErrorRoute: typeof TestErrorRoute
  PublicProjectProjectIdRoute: typeof PublicProjectProjectIdRoute
  InvitationAcceptInviteIdRoute: typeof InvitationAcceptInviteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-error': {
      id: '/test-error'
      path: '/test-error'
      fullPath: '/test-error'
      preLoaderRoute: typeof TestErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device/': {
      id: '/device/'
      path: '/'
      fullPath: '/device/'
      preLoaderRoute: typeof DeviceIndexRouteImport
      parentRoute: typeof DeviceRoute
    }
    '/public-project/$projectId': {
      id: '/public-project/$projectId'
      path: '/public-project/$projectId'
      fullPath: '/public-project/$projectId'
      preLoaderRoute: typeof PublicProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device/approve': {
      id: '/device/approve'
      path: '/approve'
      fullPath: '/device/approve'
      preLoaderRoute: typeof DeviceApproveRouteImport
      parentRoute: typeof DeviceRoute
    }
    '/auth/verify-otp': {
      id: '/auth/verify-otp'
      path: '/verify-otp'
      fullPath: '/auth/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/check-email': {
      id: '/auth/check-email'
      path: '/check-email'
      fullPath: '/auth/check-email'
      preLoaderRoute: typeof AuthCheckEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_layout/_authenticated': {
      id: '/_layout/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutAuthenticatedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/invitation/accept/$inviteId': {
      id: '/invitation/accept/$inviteId'
      path: '/invitation/accept/$inviteId'
      fullPath: '/invitation/accept/$inviteId'
      preLoaderRoute: typeof InvitationAcceptInviteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_authenticated/profile-setup': {
      id: '/_layout/_authenticated/profile-setup'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof LayoutAuthenticatedProfileSetupRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/onboarding': {
      id: '/_layout/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof LayoutAuthenticatedOnboardingRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/invitations': {
      id: '/_layout/_authenticated/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof LayoutAuthenticatedInvitationsRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/dashboard': {
      id: '/_layout/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/dashboard/': {
      id: '/_layout/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/dashboard/settings': {
      id: '/_layout/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/dashboard/invitations': {
      id: '/_layout/_authenticated/dashboard/invitations'
      path: '/invitations'
      fullPath: '/dashboard/invitations'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardInvitationsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/dashboard/workspace/create': {
      id: '/_layout/_authenticated/dashboard/workspace/create'
      path: '/workspace/create'
      fullPath: '/dashboard/workspace/create'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceCreateRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/dashboard/workspace/$workspaceId'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/dashboard/settings/workspace': {
      id: '/_layout/_authenticated/dashboard/settings/workspace'
      path: '/workspace'
      fullPath: '/dashboard/settings/workspace'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsRoute
    }
    '/_layout/_authenticated/dashboard/settings/projects': {
      id: '/_layout/_authenticated/dashboard/settings/projects'
      path: '/projects'
      fullPath: '/dashboard/settings/projects'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsRoute
    }
    '/_layout/_authenticated/dashboard/settings/account': {
      id: '/_layout/_authenticated/dashboard/settings/account'
      path: '/account'
      fullPath: '/dashboard/settings/account'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/'
      path: '/'
      fullPath: '/dashboard/workspace/$workspaceId/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/search': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/search'
      path: '/search'
      fullPath: '/dashboard/workspace/$workspaceId/search'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/overview': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/overview'
      path: '/overview'
      fullPath: '/dashboard/workspace/$workspaceId/overview'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdOverviewRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/my-tasks': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/my-tasks'
      path: '/my-tasks'
      fullPath: '/dashboard/workspace/$workspaceId/my-tasks'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMyTasksRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/members': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/members'
      path: '/members'
      fullPath: '/dashboard/workspace/$workspaceId/members'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/settings/workspace/roles': {
      id: '/_layout/_authenticated/dashboard/settings/workspace/roles'
      path: '/roles'
      fullPath: '/dashboard/settings/workspace/roles'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceRolesRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceRoute
    }
    '/_layout/_authenticated/dashboard/settings/workspace/general': {
      id: '/_layout/_authenticated/dashboard/settings/workspace/general'
      path: '/general'
      fullPath: '/dashboard/settings/workspace/general'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceRoute
    }
    '/_layout/_authenticated/dashboard/settings/account/security': {
      id: '/_layout/_authenticated/dashboard/settings/account/security'
      path: '/security'
      fullPath: '/dashboard/settings/account/security'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAccountSecurityRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRoute
    }
    '/_layout/_authenticated/dashboard/settings/account/preferences': {
      id: '/_layout/_authenticated/dashboard/settings/account/preferences'
      path: '/preferences'
      fullPath: '/dashboard/settings/account/preferences'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAccountPreferencesRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRoute
    }
    '/_layout/_authenticated/dashboard/settings/account/notifications': {
      id: '/_layout/_authenticated/dashboard/settings/account/notifications'
      path: '/notifications'
      fullPath: '/dashboard/settings/account/notifications'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAccountNotificationsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRoute
    }
    '/_layout/_authenticated/dashboard/settings/account/information': {
      id: '/_layout/_authenticated/dashboard/settings/account/information'
      path: '/information'
      fullPath: '/dashboard/settings/account/information'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAccountInformationRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRoute
    }
    '/_layout/_authenticated/dashboard/settings/account/developer': {
      id: '/_layout/_authenticated/dashboard/settings/account/developer'
      path: '/developer'
      fullPath: '/dashboard/settings/account/developer'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAccountDeveloperRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRoute
    }
    '/_layout/_authenticated/dashboard/settings/projects/$projectId/workflow': {
      id: '/_layout/_authenticated/dashboard/settings/projects/$projectId/workflow'
      path: '/$projectId/workflow'
      fullPath: '/dashboard/settings/projects/$projectId/workflow'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsRoute
    }
    '/_layout/_authenticated/dashboard/settings/projects/$projectId/visibility': {
      id: '/_layout/_authenticated/dashboard/settings/projects/$projectId/visibility'
      path: '/$projectId/visibility'
      fullPath: '/dashboard/settings/projects/$projectId/visibility'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdVisibilityRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsRoute
    }
    '/_layout/_authenticated/dashboard/settings/projects/$projectId/roles': {
      id: '/_layout/_authenticated/dashboard/settings/projects/$projectId/roles'
      path: '/$projectId/roles'
      fullPath: '/dashboard/settings/projects/$projectId/roles'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdRolesRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsRoute
    }
    '/_layout/_authenticated/dashboard/settings/projects/$projectId/members': {
      id: '/_layout/_authenticated/dashboard/settings/projects/$projectId/members'
      path: '/$projectId/members'
      fullPath: '/dashboard/settings/projects/$projectId/members'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdMembersRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsRoute
    }
    '/_layout/_authenticated/dashboard/settings/projects/$projectId/integrations': {
      id: '/_layout/_authenticated/dashboard/settings/projects/$projectId/integrations'
      path: '/$projectId/integrations'
      fullPath: '/dashboard/settings/projects/$projectId/integrations'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsRoute
    }
    '/_layout/_authenticated/dashboard/settings/projects/$projectId/general': {
      id: '/_layout/_authenticated/dashboard/settings/projects/$projectId/general'
      path: '/$projectId/general'
      fullPath: '/dashboard/settings/projects/$projectId/general'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/'
      path: '/project/$projectId'
      fullPath: '/dashboard/workspace/$workspaceId/project/$projectId/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/sprints': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/sprints'
      path: '/project/$projectId/sprints'
      fullPath: '/dashboard/workspace/$workspaceId/project/$projectId/sprints'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdSprintsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/gantt': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/gantt'
      path: '/project/$projectId/gantt'
      fullPath: '/dashboard/workspace/$workspaceId/project/$projectId/gantt'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdGanttRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/documents': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/documents'
      path: '/project/$projectId/documents'
      fullPath: '/dashboard/workspace/$workspaceId/project/$projectId/documents'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdDocumentsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/board': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/board'
      path: '/project/$projectId/board'
      fullPath: '/dashboard/workspace/$workspaceId/project/$projectId/board'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBoardRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/backlog': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/backlog'
      path: '/project/$projectId/backlog'
      fullPath: '/dashboard/workspace/$workspaceId/project/$projectId/backlog'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
    '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId_': {
      id: '/_layout/_authenticated/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId_'
      path: '/project/$projectId/task/$taskId'
      fullPath: '/dashboard/workspace/$workspaceId/project/$projectId/task/$taskId'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute
    }
  }
}

interface LayoutAuthenticatedDashboardSettingsAccountRouteChildren {
  LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute: typeof LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute
  LayoutAuthenticatedDashboardSettingsAccountInformationRoute: typeof LayoutAuthenticatedDashboardSettingsAccountInformationRoute
  LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute: typeof LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute
  LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute: typeof LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute
  LayoutAuthenticatedDashboardSettingsAccountSecurityRoute: typeof LayoutAuthenticatedDashboardSettingsAccountSecurityRoute
}

const LayoutAuthenticatedDashboardSettingsAccountRouteChildren: LayoutAuthenticatedDashboardSettingsAccountRouteChildren =
  {
    LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute:
      LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute,
    LayoutAuthenticatedDashboardSettingsAccountInformationRoute:
      LayoutAuthenticatedDashboardSettingsAccountInformationRoute,
    LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute:
      LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute,
    LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute:
      LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute,
    LayoutAuthenticatedDashboardSettingsAccountSecurityRoute:
      LayoutAuthenticatedDashboardSettingsAccountSecurityRoute,
  }

const LayoutAuthenticatedDashboardSettingsAccountRouteWithChildren =
  LayoutAuthenticatedDashboardSettingsAccountRoute._addFileChildren(
    LayoutAuthenticatedDashboardSettingsAccountRouteChildren,
  )

interface LayoutAuthenticatedDashboardSettingsProjectsRouteChildren {
  LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRoute
  LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRoute
  LayoutAuthenticatedDashboardSettingsProjectsProjectIdMembersRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdMembersRoute
  LayoutAuthenticatedDashboardSettingsProjectsProjectIdRolesRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdRolesRoute
  LayoutAuthenticatedDashboardSettingsProjectsProjectIdVisibilityRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdVisibilityRoute
  LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRoute
}

const LayoutAuthenticatedDashboardSettingsProjectsRouteChildren: LayoutAuthenticatedDashboardSettingsProjectsRouteChildren =
  {
    LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRoute:
      LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRoute,
    LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRoute:
      LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRoute,
    LayoutAuthenticatedDashboardSettingsProjectsProjectIdMembersRoute:
      LayoutAuthenticatedDashboardSettingsProjectsProjectIdMembersRoute,
    LayoutAuthenticatedDashboardSettingsProjectsProjectIdRolesRoute:
      LayoutAuthenticatedDashboardSettingsProjectsProjectIdRolesRoute,
    LayoutAuthenticatedDashboardSettingsProjectsProjectIdVisibilityRoute:
      LayoutAuthenticatedDashboardSettingsProjectsProjectIdVisibilityRoute,
    LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRoute:
      LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRoute,
  }

const LayoutAuthenticatedDashboardSettingsProjectsRouteWithChildren =
  LayoutAuthenticatedDashboardSettingsProjectsRoute._addFileChildren(
    LayoutAuthenticatedDashboardSettingsProjectsRouteChildren,
  )

interface LayoutAuthenticatedDashboardSettingsWorkspaceRouteChildren {
  LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRoute
  LayoutAuthenticatedDashboardSettingsWorkspaceRolesRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceRolesRoute
}

const LayoutAuthenticatedDashboardSettingsWorkspaceRouteChildren: LayoutAuthenticatedDashboardSettingsWorkspaceRouteChildren =
  {
    LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRoute:
      LayoutAuthenticatedDashboardSettingsWorkspaceGeneralRoute,
    LayoutAuthenticatedDashboardSettingsWorkspaceRolesRoute:
      LayoutAuthenticatedDashboardSettingsWorkspaceRolesRoute,
  }

const LayoutAuthenticatedDashboardSettingsWorkspaceRouteWithChildren =
  LayoutAuthenticatedDashboardSettingsWorkspaceRoute._addFileChildren(
    LayoutAuthenticatedDashboardSettingsWorkspaceRouteChildren,
  )

interface LayoutAuthenticatedDashboardSettingsRouteChildren {
  LayoutAuthenticatedDashboardSettingsAccountRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRouteWithChildren
  LayoutAuthenticatedDashboardSettingsProjectsRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsRouteWithChildren
  LayoutAuthenticatedDashboardSettingsWorkspaceRoute: typeof LayoutAuthenticatedDashboardSettingsWorkspaceRouteWithChildren
}

const LayoutAuthenticatedDashboardSettingsRouteChildren: LayoutAuthenticatedDashboardSettingsRouteChildren =
  {
    LayoutAuthenticatedDashboardSettingsAccountRoute:
      LayoutAuthenticatedDashboardSettingsAccountRouteWithChildren,
    LayoutAuthenticatedDashboardSettingsProjectsRoute:
      LayoutAuthenticatedDashboardSettingsProjectsRouteWithChildren,
    LayoutAuthenticatedDashboardSettingsWorkspaceRoute:
      LayoutAuthenticatedDashboardSettingsWorkspaceRouteWithChildren,
  }

const LayoutAuthenticatedDashboardSettingsRouteWithChildren =
  LayoutAuthenticatedDashboardSettingsRoute._addFileChildren(
    LayoutAuthenticatedDashboardSettingsRouteChildren,
  )

interface LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteChildren {
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMyTasksRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMyTasksRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdOverviewRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdOverviewRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBoardRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBoardRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdDocumentsRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdDocumentsRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdGanttRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdGanttRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdSprintsRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdSprintsRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdIndexRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdIndexRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRoute
}

const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteChildren: LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteChildren =
  {
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMembersRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMyTasksRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdMyTasksRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdOverviewRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdOverviewRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdSearchRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdIndexRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBacklogRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBoardRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdBoardRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdDocumentsRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdDocumentsRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdGanttRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdGanttRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdSprintsRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdSprintsRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdIndexRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdIndexRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdProjectProjectIdTaskTaskIdRoute,
  }

const LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteWithChildren =
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute._addFileChildren(
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteChildren,
  )

interface LayoutAuthenticatedDashboardRouteChildren {
  LayoutAuthenticatedDashboardInvitationsRoute: typeof LayoutAuthenticatedDashboardInvitationsRoute
  LayoutAuthenticatedDashboardSettingsRoute: typeof LayoutAuthenticatedDashboardSettingsRouteWithChildren
  LayoutAuthenticatedDashboardIndexRoute: typeof LayoutAuthenticatedDashboardIndexRoute
  LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute: typeof LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteWithChildren
  LayoutAuthenticatedDashboardWorkspaceCreateRoute: typeof LayoutAuthenticatedDashboardWorkspaceCreateRoute
}

const LayoutAuthenticatedDashboardRouteChildren: LayoutAuthenticatedDashboardRouteChildren =
  {
    LayoutAuthenticatedDashboardInvitationsRoute:
      LayoutAuthenticatedDashboardInvitationsRoute,
    LayoutAuthenticatedDashboardSettingsRoute:
      LayoutAuthenticatedDashboardSettingsRouteWithChildren,
    LayoutAuthenticatedDashboardIndexRoute:
      LayoutAuthenticatedDashboardIndexRoute,
    LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRoute:
      LayoutAuthenticatedDashboardWorkspaceWorkspaceIdRouteWithChildren,
    LayoutAuthenticatedDashboardWorkspaceCreateRoute:
      LayoutAuthenticatedDashboardWorkspaceCreateRoute,
  }

const LayoutAuthenticatedDashboardRouteWithChildren =
  LayoutAuthenticatedDashboardRoute._addFileChildren(
    LayoutAuthenticatedDashboardRouteChildren,
  )

interface LayoutAuthenticatedRouteChildren {
  LayoutAuthenticatedDashboardRoute: typeof LayoutAuthenticatedDashboardRouteWithChildren
  LayoutAuthenticatedInvitationsRoute: typeof LayoutAuthenticatedInvitationsRoute
  LayoutAuthenticatedOnboardingRoute: typeof LayoutAuthenticatedOnboardingRoute
  LayoutAuthenticatedProfileSetupRoute: typeof LayoutAuthenticatedProfileSetupRoute
}

const LayoutAuthenticatedRouteChildren: LayoutAuthenticatedRouteChildren = {
  LayoutAuthenticatedDashboardRoute:
    LayoutAuthenticatedDashboardRouteWithChildren,
  LayoutAuthenticatedInvitationsRoute: LayoutAuthenticatedInvitationsRoute,
  LayoutAuthenticatedOnboardingRoute: LayoutAuthenticatedOnboardingRoute,
  LayoutAuthenticatedProfileSetupRoute: LayoutAuthenticatedProfileSetupRoute,
}

const LayoutAuthenticatedRouteWithChildren =
  LayoutAuthenticatedRoute._addFileChildren(LayoutAuthenticatedRouteChildren)

interface LayoutRouteChildren {
  LayoutAuthenticatedRoute: typeof LayoutAuthenticatedRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthenticatedRoute: LayoutAuthenticatedRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface AuthRouteChildren {
  AuthCheckEmailRoute: typeof AuthCheckEmailRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCheckEmailRoute: AuthCheckEmailRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DeviceRouteChildren {
  DeviceApproveRoute: typeof DeviceApproveRoute
  DeviceIndexRoute: typeof DeviceIndexRoute
}

const DeviceRouteChildren: DeviceRouteChildren = {
  DeviceApproveRoute: DeviceApproveRoute,
  DeviceIndexRoute: DeviceIndexRoute,
}

const DeviceRouteWithChildren =
  DeviceRoute._addFileChildren(DeviceRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DeviceRoute: DeviceRouteWithChildren,
  TestErrorRoute: TestErrorRoute,
  PublicProjectProjectIdRoute: PublicProjectProjectIdRoute,
  InvitationAcceptInviteIdRoute: InvitationAcceptInviteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
